const SHARED_SECRET = "sharedSecretHere";
const DEFAULT_PORT = 3000;
const SIGNATURE_HEADER_NAME = "X-Signature";

exports.SHARED_SECRET = SHARED_SECRET;
exports.DEFAULT_PORT = DEFAULT_PORT;
exports.SIGNATURE_HEADER_NAME = SIGNATURE_HEADER_NAME;
